[tasks.watch]
run_task = [
  {name = ["clippy", "fmt"]}
]

watch = true

[tasks.clippy]
command = "cargo"
args = ["clippy"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.fmt]
command = "cargo"
args = ["fmt"]

[tasks.run]
command = "cargo"
args = ["run"]

